# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'file_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66ile_service.proto\"\x19\n\tDataChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"#\n\x0eUploadResponse\x12\x11\n\tunique_id\x18\x01 \x01(\t\"F\n\x0e\x45xecuteRequest\x12\x11\n\tunique_id\x18\x01 \x01(\t\x12\x0c\n\x04tool\x18\x02 \x01(\t\x12\x13\n\x0b\x63ommand_opt\x18\x03 \x01(\t\"\"\n\x0f\x45xecuteResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"5\n\x0c\x43heckRequest\x12\x11\n\tunique_id\x18\x01 \x01(\t\x12\x12\n\nresult_dir\x18\x02 \x01(\t\"#\n\rCheckResponse\x12\x12\n\nhas_stream\x18\x01 \x01(\x08\"8\n\x0f\x44ownloadRequest\x12\x11\n\tunique_id\x18\x01 \x01(\t\x12\x12\n\nresult_dir\x18\x02 \x01(\t2\xba\x01\n\x0b\x46ileService\x12\'\n\x06Upload\x12\n.DataChunk\x1a\x0f.UploadResponse(\x01\x12.\n\x07\x45xecute\x12\x0f.ExecuteRequest\x1a\x10.ExecuteResponse0\x01\x12&\n\x05\x43heck\x12\r.CheckRequest\x1a\x0e.CheckResponse\x12*\n\x08\x44ownload\x12\x10.DownloadRequest\x1a\n.DataChunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATACHUNK']._serialized_start=22
  _globals['_DATACHUNK']._serialized_end=47
  _globals['_UPLOADRESPONSE']._serialized_start=49
  _globals['_UPLOADRESPONSE']._serialized_end=84
  _globals['_EXECUTEREQUEST']._serialized_start=86
  _globals['_EXECUTEREQUEST']._serialized_end=156
  _globals['_EXECUTERESPONSE']._serialized_start=158
  _globals['_EXECUTERESPONSE']._serialized_end=192
  _globals['_CHECKREQUEST']._serialized_start=194
  _globals['_CHECKREQUEST']._serialized_end=247
  _globals['_CHECKRESPONSE']._serialized_start=249
  _globals['_CHECKRESPONSE']._serialized_end=284
  _globals['_DOWNLOADREQUEST']._serialized_start=286
  _globals['_DOWNLOADREQUEST']._serialized_end=342
  _globals['_FILESERVICE']._serialized_start=345
  _globals['_FILESERVICE']._serialized_end=531
# @@protoc_insertion_point(module_scope)
